[package]
authors = ["Will Ross <paxswill@paxswill.com>"]
edition = "2018"
license = "GPL-3.0-or-later"
name = "thermal-occupancy"
repository = "https://git.sr.ht/~paxswill/thermal-occupancy"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colorous = "1.0.3"
lazy_static = "1.4.0"
resvg = "0.14.0"
svg = "0.9.1"
tiny-skia = "0.5.0"
usvg = "0.14.0"
ndarray = "0.15.1"
linux-embedded-hal = "=0.4.0-alpha.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
tokio-stream = { version = "0.1.5", features = ["time"] }
http = "0.2.4"
warp = "0.3.1"
futures = "0.3.13"
bytes = "1.0.1"
mozjpeg = { version = "0.8.24", optional = true }

[dependencies.thermal-camera]
git = "https://git.sr.ht/~paxswill/rust-thermal-camera"
branch = "main"

[dependencies.image]
features = ["jpeg"]
version = "0.23.14"
optional = true

[dependencies.hyper]
features = ["stream"]
version = "0.14"
optional = true

[features]
default = ["mjpeg", "mozjpeg", "image"]
mjpeg = ["hyper", "tokio/sync", "tokio-stream/sync"]

[dev-dependencies]
float-cmp = "0.8.0"
fontdb = "0.5.1"
ttf-parser = "0.12.0"