[package]
name = "thermal-occupancy"
version = "0.1.0"
authors = ["Will Ross <paxswill@paxswill.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
