[package]
name = "thermal-occupancy"
version = "0.1.0"
authors = ["Will Ross <paxswill@paxswill.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colorous = "1.0.3"
image = "0.23.14"
resvg = "0.14.0"
svg = "0.9.1"
ndarray = "0.15.1"
linux-embedded-hal = "=0.4.0-alpha.0"

[dependencies.thermal-camera]
git = "https://git.sr.ht/~paxswill/rust-thermal-camera"
branch = "main"