[package]
authors = ["Will Ross <paxswill@paxswill.com>"]
edition = "2018"
license = "GPL-3.0-or-later"
name = "thermal-occupancy"
repository = "https://git.sr.ht/~paxswill/thermal-occupancy"
version = "0.1.0"

[dependencies]
bytes = "1.0.1"
colorous = "1.0.3"
futures = "0.3.13"
http = "0.2.4"
lazy_static = "1.4.0"
linux-embedded-hal = "=0.4.0-alpha.0"
mozjpeg = { version = "0.8.24", optional = true }
ndarray = "0.15.1"
resvg = { version = "0.14.0", optional = true }
svg = { version = "0.9.1", optional = true }
tiny-skia = { version = "0.5.0", optional = true }
usvg = { version = "0.14.0", optional = true }

[dependencies.hyper]
features = ["stream"]
optional = true
version = "0.14"

[dependencies.image]
features = ["jpeg"]
optional = true
version = "0.23.14"

[dependencies.thermal-camera]
branch = "main"
git = "https://git.sr.ht/~paxswill/rust-thermal-camera"

[dependencies.tokio]
features = ["macros", "rt-multi-thread", "time"]
version = "1"

[dependencies.tokio-stream]
features = ["time"]
version = "0.1.5"

[dependencies.warp]
default-features = false
version = "0.3.1"

[features]
default = ["mjpeg", "mozjpeg", "image/jpeg", "render_svg"]
mjpeg = ["hyper/stream", "tokio/sync", "tokio-stream/sync"]
render_svg = ["svg", "resvg", "tiny-skia", "usvg"]

[dev-dependencies]
float-cmp = "0.8.0"
fontdb = "0.5.1"
ttf-parser = "0.12.0"