[target.arm-unknown-linux-gnueabihf.env]
passthrough = [
    "TARGET_CFLAGS"
]

[target.arm-unknown-linux-musleabihf.env]
passthrough = [
    "TARGET_CFLAGS"
]

[target.armv7-unknown-linux-gnueabihf.env]
passthrough = [
    "TARGET_CFLAGS"
]

[target.armv7-unknown-linux-musleabihf.env]
passthrough = [
    "TARGET_CFLAGS"
]
